### PR TITLE
Support AMD in test suites

### PR DESCRIPTION
**Pull request by scottgonzalez**
This supports loading qunit-composite through AMD and also supports loading test suites that load QUnit through AMD.

### CODE REVIEW

**Comment by leobalter** [comment]
`define` is missing on the listed globals, but the code LGTM.

**Comment by jzaefferer** [comment]
Looks good.

**Comment by JamesMGreene** [comment]
Squashed (fixup-ed) as dd3f50d8c7d2c2a12aafa2ee6ed6cac50d349abf.

**Comment by JamesMGreene** [comment]
P.S. Tagged/released/published as `v1.1.0`.

**Pull request merged**
