### PR TITLE
Breaking: Consuming QUnit 2.0 APIs and removing back-compat code

### LINKED ISSUE #8: Update assertion push context for QUnit v1.15.0+
In QUnit core `v1.15.0`, `QUnit.push` was deprecated in favor of `Assert#push`.  Existing calls to `QUnit.push` in this repo should be updated to something like the following:

```js
( typeof assert.push === "function" ? assert : QUnit ).push( /* ... */ );
```

### LINKED ISSUE #9: Remove deprecated asyncTest usage in favor of assert.async for QUnit v1.16.0+
The forthcoming QUnit `v1.16.0` will deprecate `QUnit.asyncTest` in favor of a new `assert.async()` approach (see jquery/qunit#653).  This plugin should be updated to utilize this style of test as well.

More importantly, this plugin must operate in a very non-standard way that could make it inviable to use the new `assert.async()` approach as a replacement for its current use of `QUnit.stop`/`QUnit.start`. We should confirm that soon-ish as well in case we need to take an alternative approach... most likely we will just need to wrap the `done` callback in an indirect but globally available closure so it can be invoked when the child frame's test run finishes (i.e. as a replacement to [qunit-composite.js#L86-L87](https://github.com/jquery/qunit-composite/blob/92d0dd6022b66814325169ebb01e46726fca7eb4/qunit-composite.js#L86-L87)).

### PR DESCRIPTION
**Pull request by platinumazure**
Fixes #8
Fixes #9

Per discussion on the above-linked issues, this PR simply drops compatibility with QUnit <2.0.0 and thus removes some of the cruft centered around checking for different internal reporting attributes.

@JamesMGreene I'm not too happy about having to introduce two new closure variables. Please do take a good look and let me know if those could be handled better. Also, please let me know if I should be modifying the tests at all (I don't think so since the plugin functionality is meant to be unchanged).

### CODE REVIEW

**Comment by platinumazure** [comment]
And one more question: Should we consider adding a peerDependency value in package.json, to indicate that (when using QUnit as a Node module via npm) the QUnit version should also be `^2.0.0` (or you could probably get away with `>=1.18.0 <3.0.0`)?

**Comment by platinumazure** [comment]
Friendly ping @JamesMGreene.

**Comment by platinumazure** [comment]
Friendly ping @JamesMGreene (and I know you were alive since my last one). :smile:

**Comment by JamesMGreene** [comment]
@platinumazure: Hoping to finally get to this tonight. Apologies for the long delay.

**Comment by JamesMGreene** [comment]
Merged. Added the `peerDep` as mentioned. Tagged, released, and published to NPM as `v2.0.0`.

**Comment by JamesMGreene** [comment]
Thanks, Kevin!

**Comment by platinumazure** [comment]
Thanks for merging this!

**Pull request merged**
